name: pinch_scrollable
description: Pinch to zoom images in scrolling widgets. This package helps to create a scrollable set of widgets containing images with zoom effect.
version: 1.0.3
homepage: https://github.com/dadrum/pinch_scrollable

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
