name: pinch_scrollable
description: Pinch to zoom images in scrolling widgets.
version: 1.0.0
homepage: https://github.com/dadrum/pinch_scrollable

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
